ganho = float(input("Quanto vale a hora trabalhada? "))
horas = float(input("Quantas horas foram trabalhadas? "))
salario_bruto = (ganho * horas)
imposto = (salario_bruto * 0.11)
inss = (salario_bruto * 0.08)
sindicato = (salario_bruto * 0.05)
salario_liquido = (salario_bruto - imposto - inss - sindicato)
print("salario bruto: ", salario_bruto)
print("imposto: ", imposto)
print("inss: ", inss)
print("sindicato:", sindicato)
print("salario liquido: ", salario_liquido)